name: Mirror Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: couchdb
            repo: docker.io
            copyAs: couchdb
          - image: pilot
            repo: docker.io/istio
            copyAs: istio/pilot
          - image: proxyv2
            repo: docker.io/istio
            copyAs: istio/proxyv2
          - image: external-dns
            repo: bitnami
            copyAs: bitnami/external-dns
          - image: mongodb
            repo: bitnami
            copyAs: bitnami/mongodb
          - image: apiserver
            repo: docker.io/calico
            copyAs: calico/apiserver
          - image: kube-controllers
            repo: docker.io/calico
            copyAs: calico/kube-controllers
          - image: node
            repo: docker.io/calico
            copyAs: calico/node
          - image: typha
            repo: docker.io/calico
            copyAs: calico/typha
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v3
      - uses: imjasonh/setup-crane@v0.2
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Mirror
        run: |
          for tag in $(cat ./images/${{ matrix.image }}); do
            crane copy \
              ${{ matrix.repo }}/${{ matrix.image }}:$tag \
              ghcr.io/${OWNER_LC}/${{ matrix.copyAs }}:$tag
          done

